openapi: 3.0.3
info:
  title: Talantino
  version: 1.0.11
servers:
  - url: http://localhost:5000
tags:
  - name: Candidates
    description: Generate candidate data in Excel,csv,pdf formats.

paths:
  /candidates:
    post:
      tags:
        - Candidates
      summary: Create a new candidate
      description: Create a new candidate with the provided information.
      operationId: all_candidate_export
      parameters:
        - name: operation
          in: query
          required: False
          description: The operation to be performed (from query).
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object

      responses:
        "200":
          description: Candidate created successfully
          content:
            application/json:
              schema:
                type: object
        "400":
          description: Invalid input
        "422":
          description: Validation exception
